### PR TITLE
Timeout fixes

### PR DESCRIPTION
**Pull request by newville**
fixes for connection timeouts, especially so that unconnected PVs timeout in the specified time.

### CODE REVIEW

**Comment by newville** [comment]
@klauer I don't understand this failure (Py3.4 only?) and don't see how the changes made could lead to this error.  Any ideas what is going on?

**Comment by newville** [comment]
@klauer OK, and then it worked the second time.  Weird.  Is that a travis hiccup, or a subtle timing issue we should fix?

**Comment by klauer** [comment]
@newville I think it's a timing issue that should be resolved at some point. I don't think your changes had anything to do with that, though.

Looks good to me.

**Comment by newville** [comment]
OK, Thanks -  I think that connection timeouts cannot be related to that error about array values not matching.

**Pull request merged**
