### PR TITLE
ENH: access rights event handling

### PR DESCRIPTION
**Pull request by dchabot**
Addresses #76.

Todo:
- [x] basic access rights event handling
- [x] docs
- [x] tests
- [x] API changes for `PV` class

### CODE REVIEW

**Comment by klauer** [comment]
In my opinion, it would be sufficient to run callbacks such that any that care about it could check the access rights. It seems closer to the metadata that comes along with `DBR_CTRL`/`DBR_STS`, even though in the CA protocol it comes from a completely different command header.

(Only my 2c as I no longer really have any application for any of this...)

**Comment by newville** [comment]
@dchabot  Thanks very much! That looks very good on first read and without trying it.  I think I agree that this should be part of every PV, or at least on by default. 

Out of curiosity, do you know when the callback first gets called in the connection process?  Like, for how long will the access fields (`self._args['read_access']`, etc)  be `None`?  It's probably not a big deal.

Perhaps the next question is whether we should use this information to raise an error or warning if a put() or get() would violate the current access rights. 

I think  a user-supplied callback would be useful. For example, you want a GUI to be able to change color or some other property to indicate that a PV not writable.  Most of the display managers do this. I use such callbacks to indicate connection state and I think it would be useful to show when a PV has gone into "read-only" mode.

**Comment by newville** [comment]
@dchabot Thanks very much!   I agree that it looks good to go, and  I'm eager to try it out.    Since this passes all tests and is mostly (solely?) providing new features, my inclination would be to merge this.  

Anyone have any objections, concerns, or comments?

**Comment by newville** [comment]
OK, merging this,.  Thanks @dchabot !

**Pull request merged**
