### PR TITLE
epics wx.PVBitmapButton

### PR DESCRIPTION
**Pull request by vstadnytskyi**
Addresses a proposed addition in the issue #192  This pull-request will add a new Mixin class epics.wx.PVBitmapButton. We can use bitmaps built-into wx.Python via wx.ArtProvider (https://wxpython.org/Phoenix/docs/html/wx.ArtProvider.html)

Here is an example:
image

### CODE REVIEW

**Comment by vstadnytskyi** [comment]
We don't need to add .bmp images from this pull-request. I propose to you build in images from wx.Python wx.ArtProvider  library.

**Comment by newville** [comment]
@vstadnytskyi it looks to me like this PR would include image files.  Is that the intention?

**Comment by vstadnytskyi** [comment]
> @vstadnytskyi it looks to me like this PR would include image files. Is that the intention?

I have added them by a mistake. I am trying to figure out how to exclude them from the pull-request. sorry for the confusion.

**Comment by newville** [comment]
@vstadnytskyi  in the interest of not losing this contribution, I'm going to merge this and then remove the image files.

**Pull request merged**
